name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1
    - name: Build balena
      run: ls -hal && ./balena-yocto-scripts/build/barys
      shell: bash
